# Generated by Django 2.2.6 on 2022-05-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='indredientes',
            new_name='ingredientes',
        ),
    ]
